// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/test-ryan-3/models/components"
	"net/http"
)

var ListDrinksServerList = []string{
	"https://speakeasy.bar",
	"https://test.speakeasy.bar",
}

type ListDrinksRequest struct {
	// The type of drink to filter by. If not provided all drinks will be returned.
	DrinkType *components.DrinkType `queryParam:"style=form,explode=true,name=drinkType"`
}

func (o *ListDrinksRequest) GetDrinkType() *components.DrinkType {
	if o == nil {
		return nil
	}
	return o.DrinkType
}

type ListDrinksResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// An unknown error occurred interacting with the API.
	Error *components.Error
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A list of drinks.
	Classes []components.Drink
}

func (o *ListDrinksResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListDrinksResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *ListDrinksResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListDrinksResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListDrinksResponse) GetClasses() []components.Drink {
	if o == nil {
		return nil
	}
	return o.Classes
}
