/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { IngredientType } from "./ingredienttype";
import { Expose } from "class-transformer";

export class IngredientInput extends SpeakeasyBase {
    /**
     * The name of the ingredient.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The product code of the ingredient, only available when authenticated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "productCode" })
    productCode?: string;

    /**
     * The type of ingredient.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: IngredientType;
}

export class Ingredient extends SpeakeasyBase {
    /**
     * The name of the ingredient.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The product code of the ingredient, only available when authenticated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "productCode" })
    productCode?: string;

    /**
     * The number of units of the ingredient in stock, only available when authenticated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "stock" })
    stock?: number;

    /**
     * The type of ingredient.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: IngredientType;
}
