/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The type of ingredient.
 */
export enum IngredientType {
    Fresh = "fresh",
    LongLife = "long-life",
    Packaged = "packaged",
}
