/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OrderType } from "./ordertype";
import { Expose } from "class-transformer";

/**
 * An order for a drink or ingredient.
 */
export class OrderInput extends SpeakeasyBase {
    /**
     * The product code of the drink or ingredient.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "productCode" })
    productCode: string;

    /**
     * The number of units of the drink or ingredient to order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity: number;

    /**
     * The type of order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: OrderType;
}

/**
 * The status of the order.
 */
export enum OrderStatus {
    Pending = "pending",
    Processing = "processing",
    Complete = "complete",
}

/**
 * An order for a drink or ingredient.
 */
export class Order extends SpeakeasyBase {
    /**
     * The product code of the drink or ingredient.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "productCode" })
    productCode: string;

    /**
     * The number of units of the drink or ingredient to order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity: number;

    /**
     * The status of the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: OrderStatus;

    /**
     * The type of order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: OrderType;
}
