// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Security struct {
	APIKey     *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *Security) GetAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.APIKey
}

func (o *Security) GetBearerAuth() *string {
	if o == nil {
		return nil
	}
	return o.BearerAuth
}
