/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class CreateOrderRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "request, media_type=application/json",
        elemType: shared.OrderInput,
    })
    requestBody: shared.OrderInput[];

    /**
     * The url to call when the order is updated.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=callback_url" })
    callbackUrl?: string;
}

export class CreateOrderResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * An unknown error occurred interacting with the API.
     */
    @SpeakeasyMetadata()
    error?: shared.ErrorT;

    /**
     * The order was created successfully.
     */
    @SpeakeasyMetadata()
    order?: shared.Order;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
